# Generated by Django 5.2.4 on 2025-08-09 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_created_at_remove_customuser_role_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["full_names"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AddField(
            model_name="cell",
            name="cell_officer",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"user_level": "cell_officer"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_cell",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cell",
            name="hectares",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total area of the cell in hectares",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="district_officer",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"user_level": "district_officer"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_district",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="sector_officer",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"user_level": "sector_officer"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_sector",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cell",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cells",
                to="users.sector",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="national_id",
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_level",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("district_officer", "District Executive Officer"),
                    ("sector_officer", "Sector Executive Officer"),
                    ("cell_officer", "Cell Executive Officer"),
                    ("seller", "Seller"),
                    ("buyer", "Buyer"),
                    ("citizen", "Citizen"),
                ],
                default="citizen",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="users.province",
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="cell",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="villages",
                to="users.cell",
            ),
        ),
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_address", models.TextField(blank=True, null=True)),
                ("assigned_cell", models.ManyToManyField(blank=True, to="users.cell")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("assigned_cell", models.ManyToManyField(blank=True, to="users.cell")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
