# Generated by Django 5.2.4 on 2025-08-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_product_productprice_recommendedquantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_level",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("district_officer", "District Executive Officer"),
                    ("sector_officer", "Sector Executive Officer"),
                    ("cell_officer", "Cell Executive Officer"),
                    ("technician", "Technician"),
                    ("seller", "Seller"),
                    ("buyer", "Buyer"),
                    ("citizen", "Citizen"),
                ],
                default="citizen",
                max_length=20,
            ),
        ),
    ]
