# Generated by Django 5.2.4 on 2025-08-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_loginotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginotp",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="passwordresetotp",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
