# Generated by Django 5.2.4 on 2025-08-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_customuser_full_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("livestock", "Livestock"),
                    ("dairy", "Dairy"),
                    ("crops", "Crops"),
                    ("fertilizer", "Fertilizer"),
                    ("pesticides", "Pesticides"),
                    ("seeds", "Seeds"),
                    ("tools", "Tools"),
                    ("medicines", "Medicines"),
                    ("equipment", "Equipment"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
