# Generated by Django 5.2.4 on 2025-08-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_product_category"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productprice",
            unique_together=set(),
        ),
    ]
