# Generated by Django 5.2.4 on 2025-08-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_productprice_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/default.jpg",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
