# Generated by Django 5.2.4 on 2025-08-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cell",
            name="season_year",
            field=models.PositiveIntegerField(
                blank=True, default=2025, editable=False, null=True
            ),
        ),
    ]
