# Generated by Django 5.2.4 on 2025-08-17 00:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_cell_season_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cell",
            name="uuid",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
    ]
