# Generated by Django 5.2.4 on 2025-08-21 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("admin_created", "Admin Created"),
                            ("user_suspended", "User Suspended"),
                            ("profile_updated", "Profile Updated"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("otp_requested", "OTP Requested"),
                            ("otp_verified", "OTP Verified"),
                            ("password_reset_requested", "Password Reset Requested"),
                            ("password_reset_successful", "Password Reset Successful"),
                            ("sector_created", "Sector Created"),
                            ("ibabi_created", "ibabi Activity Created"),
                            ("ibabi_edited", "ibabi Activity Edited"),
                            ("ibabi_deleted", "ibabi Activity Deleted"),
                            ("assignment_made", "Officer Assigned to ibabi"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Category of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        help_text="Optional extra context (e.g. old/new values)",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        limit_choices_to={"user_level__startswith": "admin_"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="If the action was about another user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_taken_on",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminHierarchy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        help_text="The admin who added this admin",
                        limit_choices_to={
                            "user_level__in": ["super_admin", "district_officer"]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admins_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "admin",
                    models.OneToOneField(
                        help_text="The admin who was added",
                        limit_choices_to={
                            "user_level__in": ["sector_officer", "cell_officer"]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_by_admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
