# Generated by Django 5.2.4 on 2025-08-10 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_resourcerequestfeedback"),
        ("users", "0007_loginotp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="harvestreport",
            name="cell",
        ),
        migrations.RemoveField(
            model_name="harvestreport",
            name="district",
        ),
        migrations.RemoveField(
            model_name="harvestreport",
            name="province",
        ),
        migrations.RemoveField(
            model_name="harvestreport",
            name="sector",
        ),
        migrations.RemoveField(
            model_name="harvestreport",
            name="village",
        ),
        migrations.RemoveField(
            model_name="livestockproduction",
            name="cell",
        ),
        migrations.RemoveField(
            model_name="livestockproduction",
            name="district",
        ),
        migrations.RemoveField(
            model_name="livestockproduction",
            name="province",
        ),
        migrations.RemoveField(
            model_name="livestockproduction",
            name="sector",
        ),
        migrations.RemoveField(
            model_name="livestockproduction",
            name="village",
        ),
        migrations.CreateModel(
            name="Land",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("upi", models.CharField(max_length=50, unique=True)),
                ("size_hectares", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.cell"
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.district"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.province"
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.sector"
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.village"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="harvestreport",
            name="land",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="harvest_reports",
                to="report.land",
            ),
        ),
        migrations.CreateModel(
            name="LivestockLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.cell"
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.district"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livestock_locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.province"
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.sector"
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.village"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="livestockproduction",
            name="location",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productions",
                to="report.livestocklocation",
            ),
        ),
    ]
