# Generated by Django 5.2.4 on 2025-08-11 13:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0003_remove_harvestreport_cell_and_more"),
        ("users", "0009_cell_planned_crop_cell_planned_livestock_cell_season_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resourcerequest",
            name="cell",
        ),
        migrations.RemoveField(
            model_name="resourcerequest",
            name="district",
        ),
        migrations.RemoveField(
            model_name="resourcerequest",
            name="sector",
        ),
        migrations.AddField(
            model_name="land",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="land",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="land",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="land",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="livestocklocation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livestocklocation",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="livestocklocation",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="livestocklocation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="resourcerequest",
            name="delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resourcerequest",
            name="land",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_requests",
                to="report.land",
            ),
        ),
        migrations.AddField(
            model_name="resourcerequest",
            name="price_per_unit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="resourcerequest",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="resourcerequest",
            name="quantity_requested",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="land",
            unique_together={("upi", "owner")},
        ),
        migrations.AlterUniqueTogether(
            name="livestocklocation",
            unique_together={
                ("owner", "province", "district", "sector", "cell", "village")
            },
        ),
        migrations.CreateModel(
            name="SeasonalCropPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("A", "Season A"),
                            ("B", "Season B"),
                            ("C", "Season C"),
                        ],
                        max_length=1,
                    ),
                ),
                ("year", models.PositiveIntegerField(default=2025)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonal_crops",
                        to="users.cell",
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonal_plans",
                        to="users.product",
                    ),
                ),
                (
                    "set_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_seasonal_crops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "season"],
                "unique_together": {("cell", "season", "year")},
            },
        ),
        migrations.CreateModel(
            name="LandSeasonalAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_assigned", models.BooleanField(default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "land",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonal_assignments",
                        to="report.land",
                    ),
                ),
                (
                    "seasonal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="land_assignments",
                        to="report.seasonalcropplan",
                    ),
                ),
            ],
            options={
                "unique_together": {("land", "seasonal_plan")},
            },
        ),
    ]
