# Generated by Django 5.2.4 on 2025-08-12 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0004_remove_resourcerequest_cell_and_more"),
        ("users", "0010_alter_customuser_full_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestocklocation",
            name="animals",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="livestock_locations",
                to="users.product",
            ),
        ),
        migrations.AddField(
            model_name="livestocklocation",
            name="number_of_products",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of livestock or products"
            ),
        ),
        migrations.AddField(
            model_name="livestocklocation",
            name="products",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="livestock_products",
                to="users.product",
            ),
        ),
        migrations.AddField(
            model_name="resourcerequest",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resourcerequest",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.product",
            ),
        ),
    ]
