# Generated by Django 5.2.4 on 2025-08-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0006_alter_cellinventory_quantity_available_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="districtinventory",
            old_name="quantity_available",
            new_name="quantity_remaining",
        ),
        migrations.AddField(
            model_name="districtinventory",
            name="quantity_at_cell",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
