# Generated by Django 5.2.4 on 2025-08-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "report",
            "0007_rename_quantity_available_districtinventory_quantity_remaining_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="districtinventory",
            name="quantity_remaining",
        ),
        migrations.AddField(
            model_name="districtinventory",
            name="quantity_added",
            field=models.PositiveBigIntegerField(
                default=0, help_text="Total quantity added to this district inventory"
            ),
        ),
    ]
