# Generated by Django 5.2.4 on 2025-08-13 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0010_announcement_notifications"),
        ("users", "0010_alter_customuser_full_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livestockproduction",
            name="livestock_type",
        ),
        migrations.RemoveField(
            model_name="livestockproduction",
            name="production_type",
        ),
        migrations.AddField(
            model_name="livestockproduction",
            name="product",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.product",
            ),
            preserve_default=False,
        ),
    ]
