# Generated by Django 5.2.4 on 2025-08-13 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0011_remove_livestockproduction_livestock_type_and_more"),
        ("users", "0010_alter_customuser_full_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestocklocation",
            name="animals",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="livestock_locations",
                to="users.product",
            ),
        ),
        migrations.AlterField(
            model_name="livestocklocation",
            name="products",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="livestock_products",
                to="users.product",
            ),
        ),
    ]
