# Generated by Django 5.2.4 on 2025-08-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0012_alter_livestocklocation_animals_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livestocklocation",
            old_name="animals",
            new_name="animal",
        ),
        migrations.RenameField(
            model_name="livestocklocation",
            old_name="products",
            new_name="product",
        ),
    ]
