# Generated by Django 5.2.4 on 2025-08-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0013_rename_animals_livestocklocation_animal_and_more"),
        ("users", "0010_alter_customuser_full_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livestocklocation",
            name="animal",
        ),
        migrations.RemoveField(
            model_name="livestocklocation",
            name="product",
        ),
        migrations.AddField(
            model_name="livestocklocation",
            name="animals",
            field=models.ManyToManyField(
                blank=True, related_name="animal_locations", to="users.product"
            ),
        ),
        migrations.AddField(
            model_name="livestocklocation",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="product_locations", to="users.product"
            ),
        ),
    ]
