# Generated by Django 5.2.4 on 2025-08-13 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0014_remove_livestocklocation_animal_and_more"),
        ("users", "0010_alter_customuser_full_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="LivestockAnimal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.product"
                    ),
                ),
                (
                    "livestock_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="report.livestocklocation",
                    ),
                ),
            ],
            options={
                "unique_together": {("livestock_location", "animal")},
            },
        ),
    ]
