# Generated by Django 5.2.4 on 2025-08-13 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0015_livestockanimal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livestocklocation",
            name="animals",
        ),
        migrations.AlterField(
            model_name="livestockanimal",
            name="livestock_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="livestock_animals",
                to="report.livestocklocation",
            ),
        ),
    ]
