# Generated by Django 5.2.4 on 2025-08-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0016_remove_livestocklocation_animals_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="harvestreport",
            name="stutus",
            field=models.CharField(
                choices=[("sold", "Sold"), ("available", "Available")],
                default="available",
                help_text="Status of the Harvest report",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="livestocklocation",
            name="stutus",
            field=models.CharField(
                choices=[("sold", "Sold"), ("available", "Available")],
                default="available",
                help_text="Status of the livestock location",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="livestockproduction",
            name="status",
            field=models.CharField(
                choices=[("sold", "Sold"), ("available", "Available")],
                default="available",
                help_text="Status of the livestock production",
                max_length=20,
            ),
        ),
    ]
