# Generated by Django 5.2.4 on 2025-08-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0017_harvestreport_stutus_livestocklocation_stutus_and_more"),
        ("users", "0011_alter_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="harvestreport",
            old_name="stutus",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="livestocklocation",
            old_name="stutus",
            new_name="status",
        ),
        migrations.AlterField(
            model_name="livestocklocation",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="product_locations",
                to="users.product",
            ),
        ),
    ]
