# Generated by Django 5.2.4 on 2025-08-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0018_rename_stutus_harvestreport_status_and_more"),
        ("users", "0011_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestocklocation",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="product_locations", to="users.product"
            ),
        ),
    ]
