# Generated by Django 5.2.4 on 2025-08-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0019_alter_livestocklocation_products"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="livestocklocation",
            unique_together=set(),
        ),
    ]
