# Generated by Django 5.2.4 on 2025-08-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0020_alter_livestocklocation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="is_announcement",
            field=models.BooleanField(default=False),
        ),
    ]
