# Generated by Django 5.2.4 on 2025-08-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0021_notifications_is_announcement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cellclimatedata",
            old_name="forecast_data",
            new_name="next_24_hours",
        ),
        migrations.RenameField(
            model_name="cellclimatedata",
            old_name="historical_data",
            new_name="past_3_months",
        ),
    ]
