# Generated by Django 5.2.4 on 2025-08-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0022_rename_forecast_data_cellclimatedata_next_24_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellclimatedata",
            name="forecast_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cellclimatedata",
            name="historical_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
