# Generated by Django 5.2.4 on 2025-08-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0023_cellclimatedata_forecast_fetched_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cellclimatedata",
            old_name="next_24_hours",
            new_name="next_24h_forecast",
        ),
        migrations.RenameField(
            model_name="cellclimatedata",
            old_name="past_3_months",
            new_name="past_3_months_data",
        ),
    ]
