# Generated by Django 5.2.4 on 2025-08-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "report",
            "0024_rename_next_24_hours_cellclimatedata_next_24h_forecast_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cellclimatedata",
            name="next_24h_forecast",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cellclimatedata",
            name="past_3_months_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
