# Generated by Django 5.2.4 on 2025-08-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0025_alter_cellclimatedata_next_24h_forecast_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="harvestreport",
            name="report_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="livestockproduction",
            name="report_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
