# Generated by Django 5.2.4 on 2025-08-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0026_alter_harvestreport_report_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestocklocation",
            name="upi",
            field=models.CharField(
                blank=True,
                help_text="Unique Parcel Identifier for livestock location",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
