# Generated by Django 5.2.4 on 2025-08-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0027_livestocklocation_upi"),
    ]

    operations = [
        migrations.AddField(
            model_name="districtinventory",
            name="quantity_remaining_at_cells",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
