# Generated by Django 5.2.4 on 2025-08-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0029_farmerinventory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livestocklocation",
            name="status",
        ),
    ]
