# Generated by Django 5.2.4 on 2025-08-20 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0030_remove_livestocklocation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcerequest",
            name="livestock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_requests",
                to="report.livestocklocation",
            ),
        ),
        migrations.AlterField(
            model_name="resourcerequest",
            name="land",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_requests",
                to="report.land",
            ),
        ),
    ]
