# Generated by Django 5.2.4 on 2025-08-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0031_resourcerequest_livestock_alter_resourcerequest_land"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestocklocation",
            name="status",
            field=models.CharField(
                choices=[("sold", "Sold"), ("available", "Available")],
                default="available",
                help_text="Status of the Harvest report",
                max_length=20,
            ),
        ),
    ]
