# Generated by Django 5.2.4 on 2025-08-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0032_livestocklocation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestocklocation",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("sold", "Sold"), ("available", "Available")],
                default="available",
                help_text="Status of the Harvest report",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="livestockproduction",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("sold", "Sold"), ("available", "Available")],
                default="available",
                help_text="Status of the livestock production",
                max_length=20,
                null=True,
            ),
        ),
    ]
